# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    # ------------------------------------------------------------------
    # CHANGE 1: Specify the Go version and ensure caching is correct.
    # We also added the 'working-directory' to ensure this step 
    # looks for go.mod/go.sum inside the 'src' folder.
    # ------------------------------------------------------------------
    - name: Set up Go & Download Dependencies
      uses: actions/setup-go@v5 # Updated to v5 for latest features and security
      with:
        go-version: '1.20'
      working-directory: './src' # <--- IMPORTANT: Tells the action to look here

    # ------------------------------------------------------------------
    # CHANGE 2: Simplified the Build step. 
    # We removed 'cd src' and 'go mod download' (it's now in setup-go).
    # ------------------------------------------------------------------
    - name: Build
      run: go build -v cmd/main.go
      working-directory: './src' # <--- IMPORTANT: Tells the action to run here

    # ------------------------------------------------------------------
    # CHANGE 3: Run Tests. Tests also need to run from the 'src' directory.
    # ------------------------------------------------------------------
    - name: Test
      run: go test -v ./...
      working-directory: './src' # <--- IMPORTANT: Tells the action to run here
