jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # تنظیم محیط Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: true

      # --- مرحله دانلود ماژول‌ها ---
      - name: Download Go modules
        run: go mod download
        working-directory: ./src # <--- دایرکتوری را به src تغییر می‌دهد

      # --- مرحله بیلد ---
      - name: Build Executable
        run: go build -v -o myapp ./cmd # مسیردهی به main از داخل src
        working-directory: ./src # <--- دایرکتوری را به src تغییر می‌دهد

      # --- مرحله تست ---
      - name: Test
        run: go test -v ./...
        working-directory: ./src # <--- دایرکتوری را به src تغییر می‌دهد
